### ISSUE TITLE
missing files with kiauh install

### ISSUE THREAD

**Issue by robthide37** [Stephan3/dwc2-for-klipper-socket#18]
This is the error i get at the end shoud i delete and reinstall as init.d instead of system ?
###### Installing system start script...
Created symlink /etc/systemd/system/multi-user.target.wants/dwc.service → /etc/systemd/system/dwc.service.

###### Launching dwc2-for-klipper-socket...
>>>>>> Service installed!

###### Checking /etc/default/klipper for necessary entries ...
grep: /etc/default/klipper: No such file or directory

###### Patching unix domain socket to /etc/default/klipper ...
sed: can't read /etc/default/klipper: No such file or directory

**Comment by Stephan3** [comment]
@th33xitus can you comment on that ?

**Comment by dw-0** [comment]
I think there might be a bug when KIAUH checks for the klipper uds argument being present in the service file. And it seems like it checks for the init.d service files, but the user has klipper installes as systemd.

I have no intereset in fixing this bug tbh, since i am reworking KIAUH and make every service only installable via systemd anyways, and make it obsolete to "patch" an argument to that service file.

**Comment by Stephan3** [comment]
okay sounds reasonable. the next version will move forward. Thanks.
