### ISSUE TITLE
Cura gcode parsing not working quite right

### ISSUE THREAD

**Issue by guythnick** [Stephan3/dwc2-for-klipper-socket#5]
Using Cura 4.6.2, it appears the parse_gcode is not working 100%.  The filament variable is reading in meters, but storing (or at least, the display in web interface) is in millimeters.  I think multiplying by 10 in the parse code should work.

I am also having trouble with layer calculations with many of my jobs, but I can't quite put my finger on why yet.  I think the estimated time is also not parsing correctly. Perhaps it will be apparent comparing the code to the actual file output below.  

Here is the problem portion of code: 

https://github.com/Stephan3/dwc2-for-klipper-socket/blob/ffd35c7e0d43120bbc4a0d5035a9360111d6e4e2/rr_handler.py#L798-L808

Here is what is in the header output in a CURA file:

```
;FLAVOR:Marlin
;TIME:1341
;Filament used: 0.564835m
;Layer height: 0.2
;MINX:107.7
;MINY:107.7
;MINZ:0.2
;MAXX:127.3
;MAXY:127.3
;MAXZ:20
```

My list of jobs, you can see the data is either not there or incorrect:
![image](https://user-images.githubusercontent.com/5290202/93025311-95912780-f5c2-11ea-88a0-20fe2e01712e.png)

Here is a screenshot of one of my jobs that is not showing layers correctly (there are 12 layers in this one):

![image](https://user-images.githubusercontent.com/5290202/93025269-1d2a6680-f5c2-11ea-8350-884a91aef259.png)

Also including the gcode from the screenshot above:

[Greek_Meander_Lamp_part22.gcode.txt](https://github.com/Stephan3/dwc2-for-klipper-socket/files/5214822/Greek_Meander_Lamp_part22.gcode.txt)

**Comment by Stephan3** [comment]
@th33xitus this one is yours :)

i look into that

**Comment by dw-0** [comment]
@Stephan3 I haven't touched the Cura section in my last PR. But i saw that issue too. I would have fixed it but the filament is, like already mentioned, noted in meters and not in millimeters like in almost every other slicer (because Cura needs to be special right?!). So we would need a conversion step there, nothing you can do with simple regex, or?

What we could do is, grab the `MAXZ:` parameter for reading the max height of the object instead of looking for the last `G1 Z...` command like it's done now.

**Comment by lenne0815** [comment]
Sorry to interrupt but i just stumbled across a problem, for me only cura works at all, s3d and prusaslicer both give "slicer not supported". As far as i can tell its because the additional stuff here _'name': 'PrusaSlicer\s\d+.\d+.\d+',_ and here _'name': 'Simplify3D.*\s\d+.\d+.\d+',_ compared to _'name': 'Cura_SteamEngine.*',_

**Comment by dw-0** [comment]
@lenne0815 Can you provide example g-code files which don't work for you?
Before i did the PR i made sure it works... well... on my setup at least. You can see it in the screenshot i provided with the PR here: https://github.com/Stephan3/dwc2-for-klipper-socket/pull/1

**Comment by lenne0815** [comment]
Goddamnit, i just realized i installed it without your latest patch, it works now, sorry ! Huge thanks for the work from both of you !

**Comment by guythnick** [comment]
EDIT:  This code below is totally wrong... Will try to take a better look when I have more time.  PS - I appreciate @Stephan3 and @th33xitus for your work on this project.  Hopefully can be rid of that OctoPrint stutter. 

I think it will work if you use this.  In the middle of a print, so can't test it now.  But, the regex works at least for all of them. For TIME I just removed the extra "\".

```
		'Cura':
			{
				'name': 'Cura_SteamEngine.*',								#	somewhere in the first lines
				'object_h': ';MAXZ:\d*.\d',									#	get the highest knowing z
				'first_h': ';MINZ:\d*.\d',									#	get the lowest knowing z
				'layer_h': ';Layer height: \d.\d+',							#	its there
				'duration': ';TIME:\d+',									#	its there
				'filament': ';Filament used: \d*.\d+m'						#	its there
			},
```
